# -*- coding: utf-8 -*-
"""temperature_anaiysis_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16UDI83_XUy49w1oRcEyxts0paudjiNt0
"""



import numpy as np

print("==============================================================================")
print("Task 1:Create an Array and Basic Math")
print("===============================================================================")
temp_celsius=np.array([ 22, 25, 28, 24, 26])
fahrenheit= temp_celsius * 1.8 + 32
average=sum(fahrenheit)/len(fahrenheit)
print(f" celsius:{temp_celsius}")
print(f"fahrenheit:{fahrenheit}")
print(f"average of fahrenheit:{average}")

print("==============================================================================")
print("Task 2:Array Shape and Statistics")
print("===============================================================================")
arr=np.array([85, 90, 78, 92, 88, 76, 95, 82, 89, 91, 87, 84])
print("shape of array:",arr.shape)
print("total elements:",arr.size)
print("Max:",arr.max())
print("Min:",arr.min())

print("==============================================================================")
print("Task 3:Performance Comparison")
print("===============================================================================")
import time
size = 1_000_000


python_list = list(range(size))
start = time.time()
result = [x * 2 for x in python_list]
python_time = time.time() - start
print(f"Python list: {python_time:.4f} seconds")


numpy_array = np.arange(size)
start = time.time()
result = numpy_array * 2
numpy_time = time.time() - start
print(f"NumPy array: {numpy_time:.4f} seconds")


speedup = python_time / numpy_time
print(f"NumPy is {speedup:.1f}x faster!")